services:
  - type: web
    name: vehicle-intelligence
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr  # Ensure Tesseract is installed
      tesseract --version  # Verify the installation
      pip install -r requirements.txt  # Install Python dependencies
    startCommand: gunicorn main:app  # Or whatever your entry point is
    envVars:
      - key: PORT
        value: 10000